export default {
  SET_TEMPERATURE_RANGE: Symbol('SET_TEMPERATURE_START'),
  GET_TEMPERATURE_START: Symbol('GET_TEMPERATURE_START'),
  GET_TEMPERATURE_SUCCESS: Symbol('GET_TEMPERATURE_START'),
  GET_TEMPERATURE_FAILURE: Symbol('GET_TEMPERATURE_FINISH'),
};
